wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: validation/step
      6:
      - 3
    - 1: validation/loss
      5: 1
      6:
      - 1
    - 1: validation/accuracy
      5: 1
      6:
      - 1
    python_version: 3.9.5
    start_time: 1643993196
    t:
      1:
      - 1
      - 3
      - 11
      2:
      - 1
      - 3
      - 11
      3:
      - 7
      - 15
      - 16
      4: 3.9.5
      5: 0.12.9
      6: 4.11.3
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 32
betas:
  desc: null
  value:
  - 0.9
  - 0.999
dataset_name:
  desc: null
  value: cad_snli_original
device:
  desc: null
  value: cuda:0
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0001
lr_scheduler:
  desc: null
  value: cosine
model_name:
  desc: null
  value: tiny_bert
seed:
  desc: null
  value: 42
warmup_steps:
  desc: null
  value: 207
weight_decay:
  desc: null
  value: 0
